apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-app
  namespace: argocd  # Ensure this matches your ArgoCD namespace
spec:
  project: default  # Change if using a different ArgoCD project
  source:
    repoURL: "https://github.com/my-git-repo.git"
    targetRevision: "main"  # Branch, tag, or commit hash
    path: "setups/httpbin"
  destination:
    server: https://kubernetes.default.svc
    namespace: httpbin
  syncPolicy:
    automated:
      prune: false
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true