apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg-v130
spec:
  logging:
    level:
      default: warn
  provider:
    kubernetes:
      envoyDeployment:
        patch:
          value:
            metadata:
              labels:
                app.kubernetes.io/instance: echo-v2
        container: {}
        pod: {}
    type: Kubernetes