apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg-v130
spec:
  logging:
    level:
      default: warn
  provider:
    kubernetes:
        container: {}
        pod: {}
    type: Kubernetes